services:
  indexer:
    volumes:
      - type: bind
        source: /home
        target: /host_home
        read_only: true
        bind:
          propagation: rslave
      - ./config.yaml:/app/config.yaml:ro
  mcp:
    volumes:
      - type: bind
        source: /home
        target: /host_home
        read_only: true
        bind:
          propagation: rslave
      - ./config.yaml:/app/config.yaml:ro
  admin:
    volumes:
      - type: bind
        source: /home
        target: /host_home
        read_only: true
        bind:
          propagation: rslave
      - ./config.yaml:/app/config.yaml:ro
